// Contract: must match manifest.json
const CONTRACT = {
    methods: {},
    events: [],
    properties: {
        "Start": false,
        "End": false,
        "AnimationTime": 2500,
        "SourceFolderName": "Source",
        "DestinationFolderName": "Destination",
        "FileName": "File.txt"
    },
    types: {}
};

const EXTENSIONS = ['HMI'];
const TIMEOUT = 1000;

var webccInterface = function () {
    var init_ = function () {
        console.log('Animated File Transfer: Interface initialized');

        webccInterface.setProperty({ key: "Start", value: WebCC.Properties.Start });
        webccInterface.setProperty({ key: "End", value: WebCC.Properties.End });
        webccInterface.setProperty({ key: "AnimationTime", value: WebCC.Properties.AnimationTime });
        webccInterface.setProperty({ key: "SourceFolderName", value: WebCC.Properties.SourceFolderName });
        webccInterface.setProperty({ key: "DestinationFolderName", value: WebCC.Properties.DestinationFolderName });
        webccInterface.setProperty({ key: "FileName", value: WebCC.Properties.FileName });

        webccInterface.subscribe();
    };

    var setProperty_ = function (data) {
        switch (data.key) {
            case "Start":
                updateStart(data.value);
                break;
            case "AnimationTime":
                updateAnimationTime(data.value);
                break;
            case "SourceFolderName":
                updateSourceFolderName(data.value);
                break;
            case "DestinationFolderName":
                updateDestinationFolderName(data.value);
                break;
            case "FileName":
                updateFileName(data.value);
                break;
            case "End":
                // End is generated by the control. No visual action required here.
                break;
        }

        console.log('Animated File Transfer: Set property <' + data.key + '> = <' + data.value + '>');
    };

    var subscribe_ = function () {
        WebCC.onPropertyChanged.subscribe(webccInterface.setProperty);
        console.log('Animated File Transfer: Subscribe');
    };

    return {
        init: init_,
        setProperty: setProperty_,
        subscribe: subscribe_,
        contract: CONTRACT
    };
}();

var webccInterfaceInit = function () {
    webccInterface.init();

    if (WebCC.isDesignMode) {
        showDemoData();
        console.log('Animated File Transfer: Design Mode');
    } else {
        showRuntimeData();
        console.log('Animated File Transfer: Connection OK');
    }
};
